version: "3"
services:
  web1.beda.com:
    image: registry.cn-hangzhou.aliyuncs.com/d8283/nginx:v1.0
    container_name: con_nginx
    restart: always
    depends_on:
      - web2.beda.com
      - db.beda.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /pub/docker/nginx/conf:/usr/local/server/nginx/conf:ro
      - /pub/docker/nginx/html:/usr/local/server/nginx/html:ro
      - /pub/docker/nginx/logs:/usr/local/server/nginx/logs
    networks:
      - net_web
  web2.beda.com:
    image: d8283/tomcat:v2.0
    container_name: con_tomcat
    restart: always
    depends_on:
      - db.beda.com
    ports:
      - "8080:8080"    
    networks:
      - net_web
      - net_db
  db.beda.com:
    image: d8283/mysql:v1.0
    container_name: con_mysql
    restart: always
    ports:
      - "3306:3306"    
    volumes:
      - /pub/docker/mysql/etc/my.cnf:/etc/my.cnf
      - /pub/docker/mysql/data/mysql:/pub/data/mysql
      - /pub/docker/mysql/data/log:/pub/data/log
    networks:
      - net_db
networks:
  net_web:
    driver: bridge
  net_db:
    driver: bridge
