FROM registry.cn-hangzhou.aliyuncs.com/d8283/openjdk:1.8

MAINTAINER X

COPY ./sentinel-dashboard-1.8.2.jar /opt/sentinel-dashboard-1.8.2.jar

CMD java ${JAVA_OPTS} -jar /opt/sentinel-dashboard-1.8.2.jar
