apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: roles
                operator: In
                values:
                - node1
                - node2
      containers:
        - name: sentinel
          imagePullPolicy: IfNotPresent
          image: registry.cn-hangzhou.aliyuncs.com/d8283/sentinel:1.8.2
          ports:
            - containerPort: 8080
              name: sentinel-web
            - containerPort: 8719
              name: sentinel-api
          env:
            - name: JAVA_OPTS 
              value: "-Dsentinel.dashboard.auth.password=qj@1234xpxp"
  selector:
    matchLabels:
      app: sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
  labels:
    app: sentinel
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080
      name: sentinel-web
    - port: 8719
      targetPort: 8719
      nodePort: 8719
      name: sentinel-api
  clusterIP: 10.68.0.20
  type: NodePort
  selector:
    app: sentinel
